name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build Firmware for Release
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        board: [inkplate2, inkplate5v2, inkplate10, inkplate6flick]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Verify version matches version.h
        run: |
          VERSION_H=$(grep '#define FIRMWARE_VERSION "' common/src/version.h | sed 's/.*"\(.*\)".*/\1/')
          TAG_VERSION=${{ steps.get_version.outputs.version }}
          
          if [ "$VERSION_H" != "$TAG_VERSION" ]; then
            echo "❌ Error: Version mismatch!"
            echo "   version.h: $VERSION_H"
            echo "   Git tag:   v$TAG_VERSION"
            exit 1
          fi
          
          echo "✅ Version verified: $VERSION_H"
      
      - name: Cache Arduino CLI
        uses: actions/cache@v4
        with:
          path: |
            ~/.arduino15
            ~/Arduino/libraries
          key: ${{ runner.os }}-arduino-cli-1.3.1-${{ hashFiles('**/arduino-cli.yaml', '**/setup.ps1') }}
          restore-keys: |
            ${{ runner.os }}-arduino-cli-1.3.1-
      
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh -s 1.3.1
          arduino-cli version
      
      - name: Install Arduino core and libraries
        run: |
          arduino-cli config init --overwrite
          arduino-cli config set library.enable_unsafe_install true
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE/master/package_Dasduino_Boards_index.json
          arduino-cli core install Inkplate_Boards:esp32 --additional-urls https://raw.githubusercontent.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE/master/package_Dasduino_Boards_index.json
          arduino-cli lib install "InkplateLibrary"
          arduino-cli lib install "PubSubClient"
      
      - name: Build firmware
        run: |
          chmod +x build.sh
          ./build.sh ${{ matrix.board }}
      
      - name: Upload firmware artifacts (all binaries)
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.board }}-${{ steps.get_version.outputs.version }}
          path: |
            build/${{ matrix.board }}/${{ matrix.board }}-v${{ steps.get_version.outputs.version }}.bin
            build/${{ matrix.board }}/${{ matrix.board }}-v${{ steps.get_version.outputs.version }}.bootloader.bin
            build/${{ matrix.board }}/${{ matrix.board }}-v${{ steps.get_version.outputs.version }}.partitions.bin
          retention-days: 90
          if-no-files-found: error

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Extract changelog for this version
        id: changelog
        run: |
          VERSION=${{ steps.get_version.outputs.tag }}
          
          # Extract changelog section for this version
          awk "/## \[$VERSION\]/,/## \[/" CHANGELOG.md | sed '$d' > release_notes.md
          
          # If release notes are empty, use a default message
          if [ ! -s release_notes.md ]; then
            echo "Release $VERSION" > release_notes.md
            echo "" >> release_notes.md
            echo "See [CHANGELOG.md](CHANGELOG.md) for details." >> release_notes.md
          fi
          
          cat release_notes.md
      
      - name: Download all firmware artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: List and prepare downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          ls -lR artifacts/
          
          # Move binaries to root of artifacts for easier access
          find artifacts/ -name "*.bin" -type f -exec cp {} artifacts/ \;
          
          echo ""
          echo "Binaries ready for release:"
          ls -l artifacts/*.bin
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_version.outputs.tag }}
          body_path: release_notes.md
          files: artifacts/*.bin
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure jq is installed
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: Generate web flasher manifests
        env:
          TAG: ${{ steps.get_version.outputs.tag }}
        run: |
          set -euo pipefail
          
          # Generate ESP Web Tools manifests for each board
          chmod +x scripts/generate_manifests.sh
          scripts/generate_manifests.sh "${TAG}" artifacts flasher
          
          echo "Generated manifests:"
          ls -l flasher/manifest_*.json

      - name: Generate latest.json metadata
        env:
          TAG: ${{ steps.get_version.outputs.tag }}
        run: |
          set -euo pipefail
          
          # Use helper script to generate the manifest with friendly names
          chmod +x scripts/generate_latest_json.sh
          scripts/generate_latest_json.sh "${TAG}" artifacts flasher/latest.json
          
          echo "Generated latest.json:"
          ls -l flasher/latest.json

      - name: Commit manifests to main-flasher branch
        env:
          TAG: ${{ steps.get_version.outputs.tag }}
        run: |
          set -euo pipefail
          
          # Configure git
          git config user.email "actions@github.com"
          git config user.name "GitHub Action"
          
          # Save the generated manifests (they're in the working directory)
          mkdir -p /tmp/manifests
          cp flasher/manifest_*.json flasher/latest.json /tmp/manifests/
          
          # Fetch and checkout main-flasher branch (clean checkout)
          git fetch origin main-flasher
          git checkout -f main-flasher
          
          # Copy the saved manifests to the flasher directory
          cp /tmp/manifests/* flasher/
          
          # Commit and push if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            git add flasher/manifest_*.json flasher/latest.json
            git commit -m "Update flasher manifests for ${TAG} [skip ci]"
            git push origin main-flasher
            echo "✅ Manifests committed to main-flasher branch"
          else
            echo "No changes to flasher files"
          fi
